### ISSUE TITLE
Example of export a component to a package

### ISSUE THREAD

**Issue by sibelius** [kuy/redux-saga-examples#1]
How can I create a component (like a react-redux-saga-messenger) using redux and redux-saga and create a npm package that can be installed by other apps?

in the main app I want something like this

`npm install react-redux-saga-messenger --save`

``` jsx
import Messenger from 'react-redux-saga-messenger';

class App extends Component {
   render() {
       <Provider store={store}>
             <Messenger />
       </Provider>
   }
}
```

Can u add an example of this use case?

**Comment by kuy** [comment]
[Duplicated?](https://github.com/yelouafi/redux-saga/issues/394)
