### ISSUE TITLE
Example: Wizard

### ISSUE THREAD

**Issue by kuy** [kuy/redux-saga-examples#4]

**Comment by DTupalov** [comment]
In addition, example of wizard, like, payment:

Step 1. Form with firstname and lastname
Step 2. Select payment type (use request to API for avalaible types)
Step 3. Validate order (list of your items in cart)
Step 4. Agree with terms
Step 5. Make payment

In this example interesting:
- How to build saga architecture for such flow
- Handle errors while request to API (on any step)
- Backward and forward steps by user, how to handle it in saga flow

**Comment by kuy** [comment]
@DiMoNTD Done 🎉  If you have missing features, please let me know.

**Comment by DTupalov** [comment]
@kuy thanks for that awesome example. It helps me to understand some aspects of redux-saga
