### ISSUE TITLE
Example: Microblog Question

### ISSUE THREAD

**Issue by 0xpbj** [kuy/redux-saga-examples#5]
Hi @kuy, thank you for all the great examples! 

Just wondering about the work in progress tag (WIP) for the microblog example. Is there anything particular missing from the example that we should be aware of? 

I am following the example to setup event listeners for my app that uses the firebase db.

Regards.

**Comment by kuy** [comment]
@prabhaav First of all, please remember there are no issues in the current code for reference usage. "WIP" means that there is room to improve the code and it's not completed.
- Example doesn't support "remove" method
- More elegant way of integration with firebase
  - Especially, I wanted to make a bridge for pass-through firebase events and redux actions 
- No test code

If you have a question about my code, please let me know. I'm welcome 😃
